export { default as Hero } from "./Hero";
export { default as Info } from "./Info";
export { default as Tours } from "./Tours";
export { default as LeaveNumber } from "./LeaveNumber";
export { default as About } from "./About";
export { default as Gallery } from "./Gallery"
export { default as Reasons } from "./Reasons"
export { default as Address } from "./Address"
export { default as Footer } from "./Footer"